### PR TITLE
Milkcheck: Python 3 support

### PR DESCRIPTION
**Pull request by cedeyn**
Hi,

This PR makes milkcheck python3 compatible.
Enjoy :)

### CODE REVIEW

**Comment by cedeyn** [comment]
Hum, I don't undestand why " codecov/patch — 96.96% of diff hit (target 99.55%) " fails... It's not realy clear to me...

**Comment by degremont** [comment]
Thanks for the code! This is a huge patch!
It should be much easier to review if it could be splitted in simpler parts.

- Some patchs are straighforward and python3 independent (.gitignore by example).
- Some changes are simple: except .. as, string comparison with 'is' to '==', print() (don't forget import from future for that)

The dict updates seems where there could be more comments. Actually, iterating over keys() or values() in a for-loop is fine in both python2 and python3 as long as the dict is not modified in the loop, which should not be the case in most situations.

**Comment by degremont** [comment]
> Hum, I don't undestand why " codecov/patch — 96.96% of diff hit (target 99.55%) " fails... It's not realy clear to me...

If I understand correctly (https://docs.codecov.io/docs/codecov-delta) this means the tests are only covering 96.96% of the changed lines. Likely in CLI?

**Comment by cedeyn** [comment]
> Thanks for the code! This is a huge patch!
> It should be much easier to review if it could be splitted in simpler parts.
> 
>     * Some patchs are straighforward and python3 independent (.gitignore by example).
> 
>     * Some changes are simple: except .. as, string comparison with 'is' to '==', print() (don't forget import from future for that)
> 
> 
> The dict updates seems where there could be more comments. Actually, iterating over keys() or values() in a for-loop is fine in both python2 and python3 as long as the dict is not modified in the loop, which should not be the case in most situations.

Is that ok for you if I make a pull request for all commits except "milkcheck: Python3 support" and another one with splitted commit of that one ?


> If I understand correctly (https://docs.codecov.io/docs/codecov-delta) this means the tests are only > covering 96.96% of the changed lines. Likely in CLI?

Ha, ok, it's because CLI has been touched.

**Comment by cedeyn** [comment]
I'll split this pull request into smaller pieces. Closing this one.

**Pull request closed without merging**
